server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:leo_calendar}?allowMultiQueries=true
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
    # url: jdbc:mysql://sh-cynosdbmysql-grp-27qkytf8.sql.tencentcdb.com:28749/leo_calendar?allowMultiQueries=true
    # username: root
    # password: Skg4mRkJ
    # url: jdbc:mysql://127.0.0.1:3306/leo_calendar?allowMultiQueries=true
    # username: root
    # password: 123456
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
